"""
groq_client.py — auto-generated by consolidate_to_folder.py

This file is a concatenation of:
    • groq_key_rotator.py  (GROQ KEY ROTATOR)
    • groq_rotating_client.py  (GROQ ROTATING CLIENT + SHARED SINGLETON)

Do not edit the section headers below — they mark original file
boundaries for easier debugging.
"""


###########################################################################
# ─── GROQ KEY ROTATOR  (was: groq_key_rotator.py)
###########################################################################

"""
groq_key_rotator.py — Round-robin rotation across multiple Groq API keys

Purpose:
    Groq's rate limits (6000 TPM on free tier) are per-organization. If you
    own multiple Groq accounts with their own keys, you can spread load across
    them for higher effective throughput.

Usage:
    # In .env:
    #   GROQ_API_KEYS=gsk_key1,gsk_key2,gsk_key3
    # Or single key (backward-compatible):
    #   GROQ_API_KEY=gsk_single_key

    rotator = GroqKeyRotator()
    key = rotator.get_next_key()  # round-robin next available key
    if not key:
        # all keys are rate-limited, use Azure
        ...
    # Make request with key
    # On 429:
    rotator.mark_rate_limited(key)
    # On success:
    # (nothing needed — success doesn't affect rotation)

Design:
    - Round-robin: even distribution across keys
    - Cooldown: 429'd keys are skipped for 60s (Groq TPM resets per minute)
    - Thread-safe via asyncio.Lock for the rotation pointer
    - Transparent: if only one key configured, behaves like single-key

Ethical note:
    This pattern is legitimate ONLY if all keys belong to accounts YOU own
    and operate. Creating sock-puppet accounts to evade rate limits violates
    Groq's Terms of Service. Ensure the keys you provide are your own.
"""

import asyncio
import os
import time
from dataclasses import dataclass, field
from typing import Optional


# How long to skip a key after it returned 429 (seconds).
# Groq TPM limits reset every 60s, so 60s is the minimum needed.
# A small buffer (5s) helps account for clock skew.
RATE_LIMIT_COOLDOWN_SECONDS = 65.0

# How many consecutive non-429 errors before we consider a key "broken" and
# skip it longer. Protects against bad keys that return 401/403 repeatedly.
BAD_KEY_ERROR_THRESHOLD = 3
BAD_KEY_COOLDOWN_SECONDS = 300.0  # 5 minutes


@dataclass
class KeyStatus:
    """Tracks health of a single API key."""

    key: str
    label: str  # display label like "key_1"
    rate_limited_until: float = 0.0  # unix timestamp; 0 = not limited
    consecutive_errors: int = 0  # non-429 errors in a row
    bad_until: float = 0.0  # cooldown for non-429 failures
    total_success: int = 0
    total_rate_limited: int = 0
    total_errors: int = 0

    def is_available(self) -> bool:
        """True if this key can be used right now."""
        now = time.time()
        return now >= self.rate_limited_until and now >= self.bad_until

    def cooldown_remaining(self) -> float:
        """Seconds until this key becomes available again."""
        now = time.time()
        until = max(self.rate_limited_until, self.bad_until)
        return max(0.0, until - now)


class GroqKeyRotator:
    """Round-robin rotation across multiple Groq API keys.

    Picks the next available (not-rate-limited) key. Skips cooling-down keys.
    If all keys are cooling down, returns None (caller should fall back to Azure).
    """

    def __init__(self, tag: str = ""):
        self.tag = tag

        # Load keys from env:
        # - GROQ_API_KEYS (comma-separated, new multi-key format)
        # - GROQ_API_KEY  (single key, backward-compatible)
        keys = self._load_keys_from_env()

        self._keys: list[KeyStatus] = [
            KeyStatus(key=k, label=f"groq_{i + 1}") for i, k in enumerate(keys)
        ]
        self._rotation_index: int = 0
        self._lock = asyncio.Lock()

        if not self._keys:
            print(
                f"[GroqRotator] {self.tag} ⚠️  No Groq keys configured "
                f"(set GROQ_API_KEYS or GROQ_API_KEY in .env)"
            )
        else:
            print(
                f"[GroqRotator] {self.tag} ✅ Loaded {len(self._keys)} Groq key(s) "
                f"(~{len(self._keys) * 6000:,} TPM effective capacity)"
            )

    # ── Configuration loading ───────────────────────────────────────────

    def _load_keys_from_env(self) -> list[str]:
        """Load keys from env, preferring multi-key format.

        Stage R: delegates to the shared key_rotator.load_keys() so all
        services use the same env-var convention (GROQ_API_KEYS plural,
        GROQ_API_KEY singular, plus legacy numbered variants if any).
        Internal GroqRotator health tracking stays unchanged — we just
        reuse the parsing logic.
        """
        try:
            from key_rotator import load_keys as _kr_load_keys

            return _kr_load_keys("GROQ")
        except Exception:
            pass

        # Defensive fallback to legacy inline parsing if key_rotator import
        # ever fails (e.g. circular import during early bootstrap).
        keys: list[str] = []
        multi = os.environ.get("GROQ_API_KEYS", "").strip()
        if multi:
            keys = [k.strip() for k in multi.split(",") if k.strip()]
        if not keys:
            single = os.environ.get("GROQ_API_KEY", "").strip()
            if single:
                keys = [single]
        seen = set()
        unique = []
        for k in keys:
            if k not in seen:
                seen.add(k)
                unique.append(k)
        return unique

    # ── Public API ──────────────────────────────────────────────────────

    def is_enabled(self) -> bool:
        """True if any keys are configured."""
        return len(self._keys) > 0

    def get_key_count(self) -> int:
        return len(self._keys)

    async def get_next_key(self) -> Optional[tuple[str, str]]:
        """Return the next available (key, label) pair, or None if all cooling down.

        Rotation: goes through keys in order, skipping any that are cooling down.
        Returns after finding the first available one (advances pointer).
        """
        if not self._keys:
            return None

        async with self._lock:
            n = len(self._keys)
            # Try up to n keys starting from current rotation index
            for offset in range(n):
                idx = (self._rotation_index + offset) % n
                ks = self._keys[idx]
                if ks.is_available():
                    # Advance pointer past this key so NEXT call uses the one after
                    self._rotation_index = (idx + 1) % n
                    return (ks.key, ks.label)

            # All keys cooling down
            return None

    async def mark_rate_limited(self, key: str) -> None:
        """Mark a key as rate-limited. It will be skipped for RATE_LIMIT_COOLDOWN_SECONDS."""
        async with self._lock:
            ks = self._find_key(key)
            if not ks:
                return
            ks.rate_limited_until = time.time() + RATE_LIMIT_COOLDOWN_SECONDS
            ks.total_rate_limited += 1
            ks.consecutive_errors = 0  # 429 doesn't count as broken
            print(
                f"[GroqRotator] {self.tag} ⏱️  {ks.label} rate-limited "
                f"(cooldown {RATE_LIMIT_COOLDOWN_SECONDS:.0f}s, "
                f"{self._count_available_locked()}/{len(self._keys)} available)"
            )

    async def mark_error(self, key: str) -> None:
        """Mark a generic error (non-429) on a key.

        After BAD_KEY_ERROR_THRESHOLD consecutive errors, key goes on longer cooldown.
        """
        async with self._lock:
            ks = self._find_key(key)
            if not ks:
                return
            ks.consecutive_errors += 1
            ks.total_errors += 1
            if ks.consecutive_errors >= BAD_KEY_ERROR_THRESHOLD:
                ks.bad_until = time.time() + BAD_KEY_COOLDOWN_SECONDS
                ks.consecutive_errors = 0
                print(
                    f"[GroqRotator] {self.tag} ⚠️  {ks.label} disabled "
                    f"({BAD_KEY_ERROR_THRESHOLD} consecutive errors, "
                    f"cooldown {BAD_KEY_COOLDOWN_SECONDS:.0f}s)"
                )

    async def mark_success(self, key: str) -> None:
        """Mark successful use of a key. Resets consecutive error counter."""
        async with self._lock:
            ks = self._find_key(key)
            if not ks:
                return
            ks.total_success += 1
            ks.consecutive_errors = 0

    def get_stats(self) -> dict:
        """Return usage stats per key."""
        return {
            "total_keys": len(self._keys),
            "available_now": sum(1 for k in self._keys if k.is_available()),
            "per_key": [
                {
                    "label": k.label,
                    "success": k.total_success,
                    "rate_limited": k.total_rate_limited,
                    "errors": k.total_errors,
                    "available": k.is_available(),
                    "cooldown_remaining": round(k.cooldown_remaining(), 1),
                }
                for k in self._keys
            ],
        }

    def reset_all_cooldowns(self) -> None:
        """Reset all key cooldowns immediately (no server restart needed).

        Use from an admin endpoint or the Python REPL when you know Groq's
        TPM window has reset and want to un-throttle keys without waiting
        out the full cooldown period.
        """
        for ks in self._keys:
            ks.rate_limited_until = 0.0
            ks.bad_until = 0.0
            ks.consecutive_errors = 0
        print(
            f"[GroqRotator] {self.tag} 🔄 All key cooldowns reset "
            f"({len(self._keys)} key(s) now available)"
        )

    # ── Internal helpers ────────────────────────────────────────────────

    def _find_key(self, key: str) -> Optional[KeyStatus]:
        """Find KeyStatus by raw key string. Caller must hold lock."""
        for ks in self._keys:
            if ks.key == key:
                return ks
        return None

    def _count_available_locked(self) -> int:
        """Count available keys — must be called while holding lock."""
        return sum(1 for k in self._keys if k.is_available())


###########################################################################
# ─── GROQ ROTATING CLIENT + SHARED SINGLETON  (was: groq_rotating_client.py)
###########################################################################

"""
groq_rotating_client.py — Drop-in AsyncOpenAI replacement with key rotation

Purpose:
    Existing code uses `AsyncOpenAI(api_key=...)` to talk to Groq. With a
    single key, you hit 6,000 TPM limits fast. With 12 keys, you have 72,000
    TPM but the vanilla client can only hold one key at a time.

    This wrapper mimics the parts of AsyncOpenAI the codebase uses and
    rotates across keys via groq_key_rotator.GroqKeyRotator. On 429, it
    marks the key cooling and retries with the next available one.

Usage (drop-in replacement):
    # Before:
    self.client = AsyncOpenAI(
        api_key=os.environ["GROQ_API_KEY"],
        base_url="https://api.groq.com/openai/v1",
    )

    # After:
    self.client = GroqRotatingClient(tag="[Agent]")

    # All .chat.completions.create(...) calls work unchanged.
    # Streaming (stream=True) works unchanged.

Shared rotator:
    get_shared_groq_rotator() returns a process-wide singleton rotator so
    Agent, Trigger, and NLU all draw from the same 12-key pool and share
    cooldown state. This means: if Agent burns through key #3 with a 429,
    NLU knows to skip key #3 until it cools down.

Supported operations:
    - client.chat.completions.create(**kwargs) — both stream=False and stream=True
    - client.close() — releases cached per-key HTTP connections

Not supported (raise AttributeError if called):
    - Embeddings, audio, images, etc. (not used in this codebase)

Error semantics:
    - 429 (RateLimitError) on any key → mark cooling, rotate to next key
    - If all keys cooling → raises RuntimeError (caller should fall back)
    - Non-429 errors (network, 5xx, timeout) → mark error, raise immediately
    - Success → mark success (resets consecutive-error counter)
"""

import asyncio
import collections
from typing import Optional

import httpx
from openai import AsyncOpenAI
from openai import RateLimitError, APIStatusError


GROQ_BASE_URL = "https://api.groq.com/openai/v1"

# ── Connection keepalive configuration ────────────────────────────────────────
# We use TWO mechanisms to keep TCP connections warm WITHOUT spending API quota:
#
# 1. httpx pool keepalive_expiry — keeps a connection in the local pool for N
#    seconds after last use. If reused within that window, no TCP+TLS handshake.
#    Cost: zero. Just configuration.
#
# 2. TCP-level SO_KEEPALIVE — kernel sends silent TCP keepalive probes on idle
#    connections. Detects+heals dead sockets before the next HTTP request would
#    time out. Doesn't keep the connection from closing on Groq's side, but
#    catches mid-network NAT/proxy resets.
#    Cost: zero. Kernel-level packets, not API requests.
#
# What we DO NOT do anymore: send periodic chat.completions.create() pings to
# keep keys "warm". On Groq free tier (30 RPM org-wide), 12-key warmup loops
# burned 24+ req/min just for keepalive, leaving almost nothing for real
# user traffic. Functions warm_all_keys() and start_keepalive_task() now
# no-op by default. Set GROQ_KEEPALIVE_API_PINGS=1 to re-enable (only if you
# upgrade to Groq Dev tier with 300+ RPM).
KEEPALIVE_EXPIRY_SECONDS = 600.0  # 10 min — covers most proxy idle timeouts
MAX_KEEPALIVE_CONNECTIONS = 4  # per key — enough for bursts
CONNECT_TIMEOUT_SECONDS = 10.0
READ_TIMEOUT_SECONDS = 60.0  # Groq can stream for a while

# TCP-level socket keepalive (Linux/macOS). Sends silent probes on idle sockets.
TCP_KEEPALIVE_IDLE_SECONDS = 60  # start probing after 60s idle
TCP_KEEPALIVE_INTERVAL_SECONDS = 30  # probe every 30s
TCP_KEEPALIVE_PROBE_COUNT = 3  # close after 3 missed probes

# Ping interval (only used if API pings are explicitly re-enabled — see above)
KEEPALIVE_PING_INTERVAL_SECONDS = 30.0
KEEPALIVE_PING_MODEL = "llama-3.1-8b-instant"

# Master switch for the OLD API-ping behavior. Default off because it hits
# Groq free-tier rate limits hard. Re-enable only on Dev tier (300+ RPM).
import os as _kp_os

GROQ_KEEPALIVE_API_PINGS = _kp_os.environ.get("GROQ_KEEPALIVE_API_PINGS", "0") == "1"

# ── Module-level shared rotator singleton ─────────────────────────────────────
# All callers of get_shared_groq_rotator() get the SAME instance. This is how
# Agent, Trigger, and NLU share a unified view of which keys are available.
# Created lazily on first access (so env vars are read by then).
_shared_rotator: Optional[GroqKeyRotator] = None


def get_shared_groq_rotator(tag: str = "[shared]") -> GroqKeyRotator:
    """Return the process-wide shared GroqKeyRotator singleton.

    First caller's tag is used for logging. Subsequent callers get the same
    instance (their tag is ignored — this is by design for unified state).
    """
    global _shared_rotator
    if _shared_rotator is None:
        _shared_rotator = GroqKeyRotator(tag=tag)
    return _shared_rotator


# ── Namespace shims (mimic client.chat.completions.create) ────────────────────


class _CompletionsNamespace:
    """Mimics `client.chat.completions` — exposes `.create()`."""

    def __init__(self, parent: "GroqRotatingClient"):
        self._parent = parent

    async def create(self, **kwargs):
        """Forward to parent's rotation logic. Returns what AsyncOpenAI returns."""
        return await self._parent._create_with_rotation(**kwargs)


class _ChatNamespace:
    """Mimics `client.chat` — exposes `.completions` attribute."""

    def __init__(self, parent: "GroqRotatingClient"):
        self.completions = _CompletionsNamespace(parent)


# ── The rotating client ────────────────────────────────────────────────────────


class GroqRotatingClient:
    """Drop-in AsyncOpenAI replacement that rotates across multiple Groq keys.

    Compatible surface:
        client.chat.completions.create(**kwargs)  ← both streaming and non-streaming

    Internal model:
        - One underlying AsyncOpenAI instance cached per key (HTTP connection reuse)
        - Each .create() call picks a key from the rotator, calls that key's client
        - 429 → rotator.mark_rate_limited(key), retry with next key
        - Other errors → rotator.mark_error(key), raise to caller
        - Success → rotator.mark_success(key)

    Streaming note:
        For stream=True, the initial HTTP request runs synchronously before the
        stream object is returned. 429 on stream open is caught and rotated. A
        429 mid-stream (rare) will propagate to the iterator consumer — same
        behavior as today with a single-key AsyncOpenAI.
    """

    def __init__(
        self,
        rotator: Optional[GroqKeyRotator] = None,
        tag: str = "",
    ):
        """Create a rotating client.

        Args:
            rotator: Custom rotator to use. If None, uses the shared singleton.
                     Pass your own rotator only if you want an isolated key pool
                     (e.g., for testing). Default (None) is what you want.
            tag: Short label for log lines (e.g., "[Agent]", "[Trigger]").
        """
        self._rotator = rotator if rotator is not None else get_shared_groq_rotator()
        self._tag = tag
        # Per-key client cache — each AsyncOpenAI keeps its own HTTP pool
        self._clients: dict[str, AsyncOpenAI] = {}
        # Guards concurrent creation of the same-key client
        self._clients_lock = asyncio.Lock()
        # Mimic AsyncOpenAI's nested namespace access
        self.chat = _ChatNamespace(self)
        # Background keepalive task (set by start_keepalive_task)
        self._keepalive_task: Optional[asyncio.Task] = None
        # Per-key httpx clients (owned by us, passed to AsyncOpenAI)
        self._http_clients: dict[str, httpx.AsyncClient] = {}
        # Key health event log — recent rotation/exhaustion events for session insights
        self._event_log: collections.deque = collections.deque(maxlen=200)

    def _build_httpx_client(self) -> httpx.AsyncClient:
        """Build a fresh httpx AsyncClient with two layers of keepalive:

        Layer 1 — httpx pool keepalive: sockets stay in the pool for
        KEEPALIVE_EXPIRY_SECONDS (10 min) after last use, ready for instant
        reuse with no TCP+TLS handshake.

        Layer 2 — TCP socket keepalive: kernel sends silent TCP probes on idle
        sockets so dead connections (NAT/proxy timeouts) get detected and
        evicted from the pool BEFORE the next request hits a stale socket.

        Together these give "warm-feeling" connections without spending any
        API request quota — critical on Groq's 30 RPM free tier.
        """
        # Build a transport that sets SO_KEEPALIVE on every socket it opens.
        # httpx itself doesn't expose this — we hook it via the underlying
        # httpcore transport's socket-options parameter.
        try:
            import socket

            socket_options = [
                # Enable keepalive
                (socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1),
            ]
            # Linux-specific TCP_KEEPIDLE/INTVL/CNT (silently skipped on macOS)
            if hasattr(socket, "TCP_KEEPIDLE"):
                socket_options.append(
                    (
                        socket.IPPROTO_TCP,
                        socket.TCP_KEEPIDLE,
                        TCP_KEEPALIVE_IDLE_SECONDS,
                    )
                )
            if hasattr(socket, "TCP_KEEPINTVL"):
                socket_options.append(
                    (
                        socket.IPPROTO_TCP,
                        socket.TCP_KEEPINTVL,
                        TCP_KEEPALIVE_INTERVAL_SECONDS,
                    )
                )
            if hasattr(socket, "TCP_KEEPCNT"):
                socket_options.append(
                    (socket.IPPROTO_TCP, socket.TCP_KEEPCNT, TCP_KEEPALIVE_PROBE_COUNT)
                )
            # macOS uses TCP_KEEPALIVE in seconds (not the Linux triple)
            elif hasattr(socket, "TCP_KEEPALIVE"):
                socket_options.append(
                    (
                        socket.IPPROTO_TCP,
                        socket.TCP_KEEPALIVE,
                        TCP_KEEPALIVE_IDLE_SECONDS,
                    )
                )

            transport = httpx.AsyncHTTPTransport(
                limits=httpx.Limits(
                    max_keepalive_connections=MAX_KEEPALIVE_CONNECTIONS,
                    max_connections=MAX_KEEPALIVE_CONNECTIONS * 2,
                    keepalive_expiry=KEEPALIVE_EXPIRY_SECONDS,
                ),
                socket_options=socket_options,
                http2=False,
                retries=0,
            )

            return httpx.AsyncClient(
                transport=transport,
                timeout=httpx.Timeout(
                    connect=CONNECT_TIMEOUT_SECONDS,
                    read=READ_TIMEOUT_SECONDS,
                    write=10.0,
                    pool=5.0,
                ),
            )
        except Exception as e:
            # Fall back to plain httpx config if the transport-level config
            # fails (rare, but safer than crashing on a Windows oddity)
            print(
                f"[GroqRotator] ⚠️  TCP keepalive setup failed ({e}) — "
                f"falling back to pool-only keepalive"
            )
            return httpx.AsyncClient(
                limits=httpx.Limits(
                    max_keepalive_connections=MAX_KEEPALIVE_CONNECTIONS,
                    max_connections=MAX_KEEPALIVE_CONNECTIONS * 2,
                    keepalive_expiry=KEEPALIVE_EXPIRY_SECONDS,
                ),
                timeout=httpx.Timeout(
                    connect=CONNECT_TIMEOUT_SECONDS,
                    read=READ_TIMEOUT_SECONDS,
                    write=10.0,
                    pool=5.0,
                ),
                http2=False,
            )

    async def _get_client_for_key(self, key: str) -> AsyncOpenAI:
        """Get (or lazily create) the AsyncOpenAI client bound to this key.

        Uses a custom httpx client with 5-minute keepalive so connections
        survive pauses between turns.
        """
        # Fast path — no lock if already cached
        client = self._clients.get(key)
        if client is not None:
            return client
        async with self._clients_lock:
            # Re-check under lock (another coroutine may have created it)
            client = self._clients.get(key)
            if client is None:
                # Build our own httpx client with LONG keepalive — this is
                # the whole point of these changes.
                http_client = self._build_httpx_client()
                self._http_clients[key] = http_client
                client = AsyncOpenAI(
                    api_key=key,
                    base_url=GROQ_BASE_URL,
                    http_client=http_client,
                )
                self._clients[key] = client
            return client

    async def _create_with_rotation(self, **kwargs):
        """Make a chat.completions.create call with automatic 429 rotation.

        Returns whatever AsyncOpenAI returns:
            - stream=False: ChatCompletion object
            - stream=True:  AsyncStream (async iterator of ChatCompletionChunk)
        """
        if not self._rotator.is_enabled():
            raise RuntimeError(
                "GroqRotatingClient: no API keys configured "
                "(set GROQ_API_KEYS or GROQ_API_KEY in .env)"
            )

        # Cap retries at 3 to avoid stalling a live call across all keys.
        max_attempts = min(3, max(1, self._rotator.get_key_count()))
        last_error: Optional[Exception] = None
        call_ts = time.time()

        for attempt in range(max_attempts):
            key_info = await self._rotator.get_next_key()
            if key_info is None:
                # All keys cooling down — nothing to retry
                break

            key, label = key_info
            client = await self._get_client_for_key(key)

            try:
                result = await client.chat.completions.create(**kwargs)
                await self._rotator.mark_success(key)
                if attempt > 0:
                    # Log successful rotation (only interesting when we had to rotate)
                    self._event_log.append(
                        {
                            "ts": time.time(),
                            "event": "rotation_success",
                            "tag": self._tag,
                            "key_label": label,
                            "attempt": attempt + 1,
                        }
                    )
                return result

            except RateLimitError as e:
                # 429 — mark cooling and try next key
                await self._rotator.mark_rate_limited(key)
                self._event_log.append(
                    {
                        "ts": time.time(),
                        "event": "key_rate_limited",
                        "tag": self._tag,
                        "key_label": label,
                        "attempt": attempt + 1,
                    }
                )
                last_error = e
                continue

            except APIStatusError as e:
                # Other HTTP error from server (500, 502, 503, etc.)
                # Not a rate-limit issue — don't rotate, just raise.
                await self._rotator.mark_error(key)
                raise

            except asyncio.CancelledError:
                # Task cancellation — don't mark the key as broken
                raise

            except Exception as e:
                # Network/timeout/other local error — mark and raise
                await self._rotator.mark_error(key)
                raise

        # Exhausted all attempts (or none were available)
        self._event_log.append(
            {
                "ts": time.time(),
                "event": "all_keys_exhausted",
                "tag": self._tag,
                "attempts": max_attempts,
            }
        )
        if last_error is not None:
            # Re-raise the last 429 so caller sees a RateLimitError
            raise last_error
        raise RuntimeError(
            f"GroqRotatingClient {self._tag}: all "
            f"{self._rotator.get_key_count()} keys are cooling down"
        )

    def get_events_since(self, since_ts: float) -> list:
        """Return key health events logged after since_ts (unix timestamp).

        Call at session teardown to drain rotation/exhaustion events into the
        session insights log. Returns a list of dicts — empty if no events.
        """
        return [e for e in self._event_log if e.get("ts", 0) >= since_ts]

    async def warm_all_keys(self) -> None:
        """Warm up HTTP connections for every key in the rotator.

        DISABLED BY DEFAULT (set GROQ_KEEPALIVE_API_PINGS=1 to enable).

        This used to send a 1-token chat.completions.create() to each of
        your 12 keys at session start (and again every 30s via the keepalive
        loop). On Groq's free tier — where rate limits are 30 RPM applied
        ORG-WIDE, not per key — that burned 24+ requests/min purely for
        warmup, leaving almost nothing for actual user turns. This was the
        cause of the rate-limit storms in production.

        TCP+TLS warmth is now handled for free by:
          1. httpx pool keepalive (10 min — see KEEPALIVE_EXPIRY_SECONDS)
          2. SO_KEEPALIVE TCP probes (kernel-level, no API cost)

        Calling this is a no-op by default. Re-enable only on Groq Dev tier
        (300+ RPM) where the API quota cost is negligible.
        """
        if not GROQ_KEEPALIVE_API_PINGS:
            return  # no-op — see docstring

        if not self._rotator.is_enabled():
            return

        # Extract all keys from the rotator (we need direct access here,
        # not round-robin — we want to hit EVERY key)
        keys = [ks.key for ks in self._rotator._keys]  # type: ignore

        async def warm_one(key: str, label: str) -> None:
            try:
                client = await self._get_client_for_key(key)
                await asyncio.wait_for(
                    client.chat.completions.create(
                        model=KEEPALIVE_PING_MODEL,
                        messages=[{"role": "user", "content": "."}],
                        max_tokens=1,
                        temperature=0.0,
                    ),
                    timeout=10.0,
                )
            except Exception as e:
                # Warmup errors are non-fatal — the key just won't be warm
                print(
                    f"[GroqRotator] {self._tag} ⚠️  warm {label} failed: "
                    f"{type(e).__name__}"
                )

        # Warm all keys in parallel
        tasks = [
            warm_one(ks.key, ks.label)
            for ks in self._rotator._keys  # type: ignore
        ]
        await asyncio.gather(*tasks, return_exceptions=True)

        count = len(tasks)
        print(
            f"[GroqRotator] {self._tag} 🔥 Warmed {count} key(s) — "
            f"connections alive for {KEEPALIVE_EXPIRY_SECONDS:.0f}s"
        )

    def start_keepalive_task(self) -> Optional[asyncio.Task]:
        """Start a background task that pings all keys every 30s.

        DISABLED BY DEFAULT (set GROQ_KEEPALIVE_API_PINGS=1 to enable).

        Returns None when disabled. See warm_all_keys() docstring for the
        rate-limit explanation. TCP socket keepalive (kernel-level, free)
        and httpx pool keepalive (10 min) handle warmth without API quota.

        When re-enabled (Groq Dev tier only), starts a loop that calls
        warm_all_keys() every KEEPALIVE_PING_INTERVAL_SECONDS.
        """
        if not GROQ_KEEPALIVE_API_PINGS:
            return None  # no-op — see warm_all_keys docstring

        if self._keepalive_task is not None and not self._keepalive_task.done():
            return self._keepalive_task

        async def _keepalive_loop() -> None:
            print(
                f"[GroqRotator] {self._tag} 💓 keepalive loop started "
                f"(interval={KEEPALIVE_PING_INTERVAL_SECONDS:.0f}s)"
            )
            try:
                while True:
                    await asyncio.sleep(KEEPALIVE_PING_INTERVAL_SECONDS)
                    try:
                        await self.warm_all_keys()
                    except Exception as e:
                        # Never let keepalive crash the session
                        print(
                            f"[GroqRotator] {self._tag} ⚠️  keepalive "
                            f"iteration failed: {e}"
                        )
            except asyncio.CancelledError:
                print(f"[GroqRotator] {self._tag} 💓 keepalive loop stopped")
                raise

        self._keepalive_task = asyncio.create_task(_keepalive_loop())
        return self._keepalive_task

    async def close(self) -> None:
        """Close all cached per-key AsyncOpenAI + httpx clients and stop keepalive."""
        # Stop keepalive task first
        if self._keepalive_task is not None and not self._keepalive_task.done():
            self._keepalive_task.cancel()
            try:
                await self._keepalive_task
            except (asyncio.CancelledError, Exception):
                pass
            self._keepalive_task = None

        async with self._clients_lock:
            for client in self._clients.values():
                try:
                    await client.close()
                except Exception:
                    pass
            self._clients.clear()
            # Also close our owned httpx clients
            for http_client in self._http_clients.values():
                try:
                    await http_client.aclose()
                except Exception:
                    pass
            self._http_clients.clear()

    def get_stats(self) -> dict:
        """Return rotator stats — useful for diagnostics endpoints."""
        return self._rotator.get_stats()

    @property
    def key_count(self) -> int:
        """Number of keys in the rotator pool."""
        return self._rotator.get_key_count()
