"""
storage.py — auto-generated by consolidate_to_folder.py

This file is a concatenation of:
    • session_store.py  (SESSION + SETTINGS + CONVERSATION STORAGE)

Do not edit the section headers below — they mark original file
boundaries for easier debugging.
"""


###########################################################################
# ─── SESSION + SETTINGS + CONVERSATION STORAGE  (was: session_store.py)
###########################################################################

"""
session_store.py — JSON file-based persistence

Stores:
  - sessions.json: meeting history (transcript, action items, Jira keys)
  - settings.json: Jira/Azure config (editable from UI)
  - pending_tickets.json: failed Jira tickets for retry
"""

import json
import os
import time
import threading

SESSIONS_FILE = os.environ.get("SESSIONS_FILE", "sessions.json")
SETTINGS_FILE = os.environ.get("SETTINGS_FILE", "settings.json")
PENDING_FILE = os.environ.get("PENDING_FILE", "pending_tickets.json")
CONVERSATIONS_FILE = os.environ.get("CONVERSATIONS_FILE", "conversation_summaries.json")
# Phase 2+3: per-session setup + user-scoped agenda templates
MEETING_SETUPS_FILE = os.environ.get("MEETING_SETUPS_FILE", "meeting_setups.json")
AGENDA_TEMPLATES_FILE = os.environ.get("AGENDA_TEMPLATES_FILE", "agenda_templates.json")
INSIGHTS_FILE = os.environ.get("INSIGHTS_FILE", "session_insights.json")
_lock = threading.Lock()


# ── Generic JSON helpers ──────────────────────────────────────────────────────


def _load_json(path: str, default=None):
    try:
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
    except Exception as e:
        print(f"[Store] ⚠️  Load {path} failed: {e}")
    return default if default is not None else {}


def _save_json(path: str, data):
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str, ensure_ascii=False)
    except Exception as e:
        print(f"[Store] ⚠️  Save {path} failed: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# SESSION HISTORY
# ══════════════════════════════════════════════════════════════════════════════


def save_session(session_data: dict):
    with _lock:
        sessions = _load_json(SESSIONS_FILE, [])
        sessions.insert(0, session_data)
        if len(sessions) > 200:
            sessions = sessions[:200]
        _save_json(SESSIONS_FILE, sessions)
    sid = session_data.get("session_id", "?")[:12]
    print(
        f"[SessionStore] 💾 Saved session {sid} ({len(session_data.get('action_items', []))} items)"
    )


def get_sessions(limit: int = 50, user: str = None) -> list[dict]:
    sessions = _load_json(SESSIONS_FILE, [])
    # Defensive filter: standups belong in the Standups tab, not Sessions.
    # This hides any historical standup entries that were saved before the
    # save-side guard in _post_meeting_save was added.
    sessions = [s for s in sessions if s.get("mode") != "standup"]
    if user:
        sessions = [s for s in sessions if s.get("user") == user]
    summaries = []
    for s in sessions[:limit]:
        summaries.append(
            {
                "session_id": s.get("session_id", ""),
                "date": s.get("date", ""),
                "user": s.get("user", ""),
                "mode": s.get("mode", "client_call"),
                "project": s.get("project", ""),
                "meeting_url": s.get("meeting_url", ""),
                "duration_minutes": s.get("duration_minutes", 0),
                "summary": s.get("summary", ""),
                "feedback_count": s.get("feedback_count", 0),
                "tickets_created": s.get("tickets_created", 0),
                "action_items": s.get("action_items", []),
            }
        )
    return summaries


def get_session_detail(session_id: str) -> dict | None:
    sessions = _load_json(SESSIONS_FILE, [])
    for s in sessions:
        if s.get("session_id") == session_id:
            return s
    return None


# ══════════════════════════════════════════════════════════════════════════════
# SETTINGS (Jira/Azure config, editable from UI)
# ══════════════════════════════════════════════════════════════════════════════


def load_settings() -> dict:
    """Load saved settings. Falls back to env vars if no settings file."""
    saved = _load_json(SETTINGS_FILE, {})
    return {
        "jira_url": saved.get("jira_url", os.environ.get("JIRA_BASE_URL", "")),
        "jira_email": saved.get("jira_email", os.environ.get("JIRA_EMAIL", "")),
        "jira_token": saved.get("jira_token", os.environ.get("JIRA_API_TOKEN", "")),
        "jira_project": saved.get(
            "jira_project", os.environ.get("JIRA_DEFAULT_PROJECT", "")
        ),
        "jira_sprint": saved.get("jira_sprint", ""),
        "azure_endpoint": saved.get(
            "azure_endpoint", os.environ.get("AZURE_ENDPOINT", "")
        ),
        "azure_key": saved.get("azure_key", os.environ.get("AZURE_API_KEY", "")),
        "azure_deployment": saved.get(
            "azure_deployment", os.environ.get("AZURE_DEPLOYMENT", "gpt-4o-mini")
        ),
        # ── Simli (was missing — caused enabled toggle to always read False) ──
        "simli_enabled": bool(saved.get("simli_enabled", False)),
        "simli_api_key": saved.get(
            "simli_api_key", os.environ.get("SIMLI_API_KEY", "")
        ),
        "simli_face_id": saved.get(
            "simli_face_id", os.environ.get("SIMLI_FACE_ID", "")
        ),
    }


def save_settings(settings: dict):
    """Save settings to file AND update env vars for current process."""
    with _lock:
        _save_json(SETTINGS_FILE, settings)
    # Also update env vars so JiraClient picks them up on next init
    env_map = {
        "jira_url": "JIRA_BASE_URL",
        "jira_email": "JIRA_EMAIL",
        "jira_token": "JIRA_API_TOKEN",
        "jira_project": "JIRA_DEFAULT_PROJECT",
        "azure_endpoint": "AZURE_ENDPOINT",
        "azure_key": "AZURE_API_KEY",
        "azure_deployment": "AZURE_DEPLOYMENT",
        "simli_api_key": "SIMLI_API_KEY",
        "simli_face_id": "SIMLI_FACE_ID",
    }
    for key, env_name in env_map.items():
        val = settings.get(key, "")
        if val:
            os.environ[env_name] = val
    print(
        f"[Settings] 💾 Saved + env updated (project: {settings.get('jira_project', '?')})"
    )


# ══════════════════════════════════════════════════════════════════════════════
# PENDING TICKETS (failed Jira creates — retry later)
# ══════════════════════════════════════════════════════════════════════════════


def save_pending_ticket(ticket_data: dict):
    """Save a failed ticket for later retry."""
    with _lock:
        pending = _load_json(PENDING_FILE, [])
        ticket_data["failed_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        pending.append(ticket_data)
        _save_json(PENDING_FILE, pending)
    print(f"[Pending] 💾 Saved pending ticket: {ticket_data.get('summary', '?')[:50]}")


def get_pending_tickets() -> list[dict]:
    return _load_json(PENDING_FILE, [])


def clear_pending_tickets():
    with _lock:
        _save_json(PENDING_FILE, [])
    print("[Pending] 🗑️  Cleared all pending tickets")


def remove_pending_ticket(index: int):
    """Remove a single pending ticket by index after successful sync."""
    with _lock:
        pending = _load_json(PENDING_FILE, [])
        if 0 <= index < len(pending):
            pending.pop(index)
            _save_json(PENDING_FILE, pending)


# ══════════════════════════════════════════════════════════════════════════════
# STANDUPS (structured developer standup data)
# ══════════════════════════════════════════════════════════════════════════════

STANDUPS_FILE = os.environ.get("STANDUPS_FILE", "standups.json")


def save_standup(standup_data: dict):
    """Save or update a standup (upsert by developer+date)."""
    dev = standup_data.get("developer", "?")
    date = standup_data.get("date", "?")
    with _lock:
        standups = _load_json(STANDUPS_FILE, [])
        # Replace existing entry for same developer+date (enriched overwrites basic)
        standups = [
            s
            for s in standups
            if not (s.get("developer") == dev and s.get("date") == date)
        ]
        standups.insert(0, standup_data)
        if len(standups) > 500:
            standups = standups[:500]
        _save_json(STANDUPS_FILE, standups)
    print(f"[Standup] 💾 Saved standup for {dev} on {date}")


def get_team_standups(date: str = None, user: str = None) -> list[dict]:
    """Get all standups for a given date (defaults to today).
    Returns list of standup summaries for the PM dashboard."""
    if not date:
        date = time.strftime("%Y-%m-%d", time.gmtime())
    standups = _load_json(STANDUPS_FILE, [])
    results = []
    for s in standups:
        if s.get("date") != date:
            continue
        results.append(
            {
                "developer": s.get("developer", "?"),
                "date": s.get("date", ""),
                "completed": s.get("completed", False),
                "started_at": s.get("started_at", ""),
                "completed_at": s.get("completed_at", ""),
                "yesterday": s.get("yesterday", {}).get("summary", ""),
                "today": s.get("today", {}).get("summary", ""),
                "blockers": s.get("blockers", {}).get("summary", "No blockers"),
                "yesterday_raw": s.get("yesterday", {}).get("raw", ""),
                "today_raw": s.get("today", {}).get("raw", ""),
                "blockers_raw": s.get("blockers", {}).get("raw", ""),
                "blocker_count": len(s.get("blockers", {}).get("items", [])),
                "has_real_blocker": s.get(
                    "has_real_blocker", None
                ),  # None = not classified (old data)
                "jira_ids": s.get("all_jira_ids", []),
                "one_line_summary": s.get("one_line_summary", ""),
            }
        )
    return results


def get_standup_detail(developer: str, date: str = None) -> dict | None:
    """Get full standup detail for a specific developer on a date."""
    if not date:
        date = time.strftime("%Y-%m-%d", time.gmtime())
    standups = _load_json(STANDUPS_FILE, [])
    for s in standups:
        if s.get("developer") == developer and s.get("date") == date:
            return s
    return None


def get_previous_standup(developer: str) -> dict | None:
    """Get the most recent standup for a developer from a PREVIOUS day (not today)."""
    today = time.strftime("%Y-%m-%d", time.gmtime())
    standups = _load_json(STANDUPS_FILE, [])
    for s in standups:
        if (
            s.get("developer") == developer
            and s.get("completed")
            and s.get("date") != today
        ):
            return s
    return None


# ══════════════════════════════════════════════════════════════════════════════
# CONVERSATION-SCOPED MEMORY (Feature 4 Memory)
# ══════════════════════════════════════════════════════════════════════════════
#
# Memory is keyed by conversation_id = hash(sorted(attendee names)).
# Same group of people meeting again → same ID → loads prior summaries.
# Different group → different ID → fresh start (privacy-safe by design).


def save_conversation_summary(
    conversation_id: str, summary: dict, participants: list, session_id: str = ""
):
    """Save a meeting summary under a conversation_id.

    summary: dict with topics, decisions, commitments, open_items,
             tickets_referenced, summary_text (see SESSION_SUMMARY_PROMPT).
    participants: list of attendee names (for debugging, not used for lookup).
    session_id: optional link back to the raw session record.
    """
    if not conversation_id:
        print("[Store] ⚠️  save_conversation_summary: empty conversation_id, skipping")
        return

    with _lock:
        summaries = _load_json(CONVERSATIONS_FILE, [])

        entry = {
            "conversation_id": conversation_id,
            "participants": sorted(participants) if participants else [],
            "date": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "session_id": session_id,
            "summary": summary,
        }
        summaries.insert(0, entry)

        # Cap total stored summaries to prevent runaway growth (keep newest 1000)
        if len(summaries) > 1000:
            summaries = summaries[:1000]

        _save_json(CONVERSATIONS_FILE, summaries)
        print(
            f"[Store] 💾 Saved summary for conv_id={conversation_id[:8]}... "
            f"participants={entry['participants']}"
        )


def get_conversation_summaries(conversation_id: str, limit: int = 3) -> list[dict]:
    """Load the most recent N summaries for a conversation_id.
    Returns list newest-first. Empty list if no history or bad input.
    """
    if not conversation_id:
        return []

    summaries = _load_json(CONVERSATIONS_FILE, [])
    matching = [s for s in summaries if s.get("conversation_id") == conversation_id]

    # Already sorted newest-first because we insert at index 0
    return matching[:limit]


def get_all_conversations() -> list[dict]:
    """Debug/admin helper: return all conversation summaries.
    Useful for inspecting what memory exists.
    """
    return _load_json(CONVERSATIONS_FILE, [])


# ══════════════════════════════════════════════════════════════════════════════
# PHASE 2+3: MEETING SETUP (per-session agenda/tickets/scope)
# ══════════════════════════════════════════════════════════════════════════════


def save_meeting_setup(session_id: str, setup: dict):
    """Store setup data for a session (before Sam joins).

    setup shape:
        {
            "agenda": [{"id": "topic_1", "title": "...", "status": "pending"}, ...],
            "scope_in": [str, ...],
            "scope_out": [str, ...],
            "ticket_keys": ["SCRUM-244", ...],
            "planned_duration_minutes": 30,
            "template_name": str or None  (if loaded from template)
        }
    """
    with _lock:
        setups = _load_json(MEETING_SETUPS_FILE, {})
        setup["saved_at"] = time.time()
        setups[session_id] = setup
        # Prune: keep last 50 by timestamp
        if len(setups) > 50:
            items = sorted(
                setups.items(), key=lambda kv: kv[1].get("saved_at", 0), reverse=True
            )[:50]
            setups = dict(items)
        _save_json(MEETING_SETUPS_FILE, setups)


def get_meeting_setup(session_id: str) -> dict | None:
    """Load setup for a session. Returns None if not found."""
    with _lock:
        setups = _load_json(MEETING_SETUPS_FILE, {})
    return setups.get(session_id)


def delete_meeting_setup(session_id: str):
    """Remove setup (e.g., after session ends). Non-fatal on miss."""
    with _lock:
        setups = _load_json(MEETING_SETUPS_FILE, {})
        setups.pop(session_id, None)
        _save_json(MEETING_SETUPS_FILE, setups)


# ══════════════════════════════════════════════════════════════════════════════
# PHASE 2+3: AGENDA TEMPLATES (per-user reusable templates)
# ══════════════════════════════════════════════════════════════════════════════


def save_agenda_template(user: str, name: str, template: dict):
    """Save or update an agenda template for a user.

    template shape: same as setup, minus session-specific fields
        {
            "agenda": [...],
            "scope_in": [...],
            "scope_out": [...],
            "ticket_keys": [...],  (optional — commonly-used tickets)
        }
    """
    if not user or not name:
        raise ValueError("user and name required")
    with _lock:
        all_templates = _load_json(AGENDA_TEMPLATES_FILE, {})
        user_templates = all_templates.get(user, {})
        template["name"] = name
        template["updated_at"] = time.time()
        user_templates[name] = template
        all_templates[user] = user_templates
        _save_json(AGENDA_TEMPLATES_FILE, all_templates)


def get_agenda_templates(user: str) -> list[dict]:
    """Return list of templates for a user, most-recently-updated first."""
    with _lock:
        all_templates = _load_json(AGENDA_TEMPLATES_FILE, {})
    user_templates = all_templates.get(user, {})
    items = list(user_templates.values())
    items.sort(key=lambda t: t.get("updated_at", 0), reverse=True)
    return items


def delete_agenda_template(user: str, name: str) -> bool:
    """Remove a template. Returns True if removed, False if not found."""
    with _lock:
        all_templates = _load_json(AGENDA_TEMPLATES_FILE, {})
        user_templates = all_templates.get(user, {})
        if name not in user_templates:
            return False
        user_templates.pop(name)
        all_templates[user] = user_templates
        _save_json(AGENDA_TEMPLATES_FILE, all_templates)
    return True


# ══════════════════════════════════════════════════════════════════════════════
# SESSION INSIGHTS (per-utterance sentiment / emotion / intent log)
# Written to INSIGHTS_FILE (session_insights.json) independently of
# sessions.json / standups.json so existing schemas are never touched.
#
# Structure: list of session records, each keyed by session_id:
#   [
#     {
#       "session_id": "...",
#       "session_type": "standup" | "client_call",
#       "date": "2026-05-21",
#       "participants": [...],
#       "transcript": [ ...per-utterance dicts... ],
#       "session_summary": { overall_sentiment, dominant_emotion, ... }
#     },
#     ...
#   ]
# ══════════════════════════════════════════════════════════════════════════════


def _find_or_create_insights_record(records: list, session_id: str) -> dict:
    """Find an existing record for session_id or create and append a stub."""
    for rec in records:
        if rec.get("session_id") == session_id:
            return rec
    stub = {
        "session_id": session_id,
        "session_type": "",
        "date": "",
        "participants": [],
        "transcript": [],
        "session_summary": {},
    }
    records.insert(0, stub)
    return stub


def append_utterance_insight(session_id: str, utterance_record: dict) -> None:
    """Append one per-utterance insight record to INSIGHTS_FILE in real-time.

    Thread-safe. Retries once after 200ms on OSError (file locked by
    another process). Never raises — logging must not break main flow.

    utterance_record shape:
        {
            "timestamp": "2026-05-21T16:40:54Z",
            "speaker": "Dev Sam",
            "utterance": "I've been working on ...",
            "sentiment": {"label": "positive", "score": 0.87},  # score from Deepgram (null if unavailable)
            "emotions":  {"dominant": "focused", "scores": {...}},
            "intent":    {"label": "providing_update", "score": 0.5},
            "filler_triggered": false,
            "pause_detected": false,
            "adaptive_endpointing_used": "fast"|"medium"|"slow"|null,
            "active_listening_token_played": "Hmm"|null,
            "bridge_filler_played": null,
        }
    """
    for attempt in range(2):
        try:
            with _lock:
                records = _load_json(INSIGHTS_FILE, [])
                rec = _find_or_create_insights_record(records, session_id)
                rec["transcript"].append(utterance_record)
                _save_json(INSIGHTS_FILE, records)
            return
        except OSError as e:
            if attempt == 0:
                import time as _t

                _t.sleep(0.2)
            else:
                print(f"[Insights] ⚠️  append_utterance_insight failed after retry: {e}")
        except Exception as e:
            print(f"[Insights] ⚠️  append_utterance_insight error (non-fatal): {e}")
            return


def save_session_insights(
    session_id: str,
    session_type: str,
    date: str,
    participants: list,
    summary: dict,
) -> None:
    """Merge session-level metadata and summary into the insights record.

    Called once when a session ends (after all per-utterance appends).
    Fills in session_type, date, participants, and session_summary fields.
    Thread-safe. Never raises.
    """
    try:
        with _lock:
            records = _load_json(INSIGHTS_FILE, [])
            rec = _find_or_create_insights_record(records, session_id)
            rec["session_type"] = session_type
            rec["date"] = date
            rec["participants"] = participants
            rec["session_summary"] = summary
            _save_json(INSIGHTS_FILE, records)
        sid = session_id[:12]
        print(
            f"[Insights] 💾 Saved session summary for {sid} "
            f"({session_type}, {len(rec['transcript'])} utterances)"
        )
    except Exception as e:
        print(f"[Insights] ⚠️  save_session_insights failed (non-fatal): {e}")


def get_session_insights(session_id: str) -> dict | None:
    """Load the full insights record for a session. Returns None if not found."""
    records = _load_json(INSIGHTS_FILE, [])
    for rec in records:
        if rec.get("session_id") == session_id:
            return rec
    return None
