"""
stt.py — auto-generated by consolidate_to_folder.py

This file is a concatenation of:
    • vad.py  (VOICE ACTIVITY DETECTION)
    • stt_clients.py  (STT WEBSOCKET CLIENTS)
    • flux_session_manager.py  (FLUX SESSION MANAGER)

Do not edit the section headers below — they mark original file
boundaries for easier debugging.
"""


###########################################################################
# ─── VOICE ACTIVITY DETECTION  (was: vad.py)
###########################################################################

"""
vad.py — RMS Energy-based Voice Activity Detection

Silero VAD doesn't work with Google Meet audio from Recall.ai
(WebRTC processing alters spectral characteristics → max conf 0.066).

RMS energy detection works perfectly:
  Speech RMS: 0.01 - 0.35
  Silence RMS: 0.00001
  Separation: 1000x+

No model download, no ONNX, no PyTorch. Just numpy math.
Processes 32ms audio chunks, same interface as Silero version.
"""

import time
import numpy as np


class RmsVAD:
    """RMS energy-based Voice Activity Detection.

    Drop-in replacement for SileroVAD with identical interface.
    Calibrated on actual Recall.ai Google Meet audio.
    """

    SAMPLE_RATE = 16000
    CHUNK_SAMPLES = 512  # 32ms at 16kHz (same as Silero)
    RMS_THRESHOLD = 0.01  # RMS above this = speech (ambient noise sits at 0.003-0.008)
    SILENCE_FLOOR = 0.0003  # Below this = absolute silence
    DIRECT_SPEECH_RMS = 0.06  # Peak RMS must exceed this for flush (headset mic: 0.08+, background: <0.05)

    def __init__(self):
        self._ready = False
        self._audio_buffer = np.array([], dtype=np.float32)

        # State tracking (same interface as SileroVAD)
        self.is_speaking = False
        self.speech_start = 0.0
        self.silence_start = 0.0
        self.last_confidence = 0.0  # stores RMS value (0.0-1.0)
        self.heard_speech = False  # sticky flag — True until end_turn()
        self.last_speech_time = 0.0  # when RMS last exceeded threshold
        self.peak_rms = 0.0  # highest RMS since last end_turn()

    async def setup(self):
        """No model to download — just mark ready."""
        self._ready = True
        print("[VAD] ✅ RMS energy VAD ready (no model needed, ~0ms/chunk)")

    def process_chunk(self, pcm_bytes: bytes) -> list[float]:
        """Feed raw PCM bytes (16kHz S16LE mono). Returns list of RMS values."""
        if not self._ready:
            return []

        samples = np.frombuffer(pcm_bytes, dtype=np.int16).astype(np.float32) / 32768.0
        self._audio_buffer = np.concatenate([self._audio_buffer, samples])

        rms_values = []
        while len(self._audio_buffer) >= self.CHUNK_SAMPLES:
            chunk = self._audio_buffer[: self.CHUNK_SAMPLES]
            self._audio_buffer = self._audio_buffer[self.CHUNK_SAMPLES :]
            rms = float(np.sqrt(np.mean(chunk**2)))
            rms_values.append(rms)

        return rms_values

    def update_state(self, rms: float, threshold: float = None):
        """Update speaking/silence tracking from RMS value.

        Args:
            rms: RMS energy level (0.0-1.0)
            threshold: Ignored — uses calibrated RMS_THRESHOLD
        """
        thresh = self.RMS_THRESHOLD
        self.last_confidence = rms
        now = time.time()

        if rms >= thresh:
            # Speech energy detected
            self.heard_speech = True
            self.last_speech_time = now
            self.silence_start = 0.0
            # Track loudest sound this turn — used to filter background voices
            if rms > self.peak_rms:
                self.peak_rms = rms
            if not self.is_speaking:
                self.is_speaking = True
                self.speech_start = now
                print(f"[VAD] 🎙️ Speech detected (rms={rms:.4f})")
        else:
            # Below threshold — track silence
            if self.heard_speech and self.silence_start == 0.0:
                self.silence_start = now
            # Reset is_speaking after 3s of silence (but keep heard_speech!)
            if self.is_speaking and self.silence_start > 0.0:
                if (now - self.silence_start) > 3.0:
                    self.is_speaking = False

    def silence_duration_ms(self) -> float:
        """Milliseconds of continuous silence. 0 if no silence started."""
        if not self.heard_speech or self.silence_start == 0.0:
            return 0.0
        return (time.time() - self.silence_start) * 1000

    def silence_since_last_speech_ms(self) -> float:
        """Milliseconds since last speech detected."""
        if not self.heard_speech or self.last_speech_time == 0.0:
            return 0.0
        if self.silence_start == 0.0:
            return 0.0
        return (time.time() - self.last_speech_time) * 1000

    def end_turn(self):
        """Mark turn as finished. Call after flushing buffer."""
        self.is_speaking = False
        self.silence_start = 0.0
        self.speech_start = 0.0
        self.heard_speech = False
        self.last_speech_time = 0.0
        self.peak_rms = 0.0

    @property
    def is_direct_speech(self) -> bool:
        """True if peak RMS this turn exceeded direct-speech threshold.
        Background voices: peak 0.01-0.02, direct mic: peak 0.03+"""
        return self.peak_rms >= self.DIRECT_SPEECH_RMS

    def reset(self):
        """Full reset — call between meetings."""
        self._audio_buffer = np.array([], dtype=np.float32)
        self.end_turn()
        self.last_confidence = 0.0

    @property
    def ready(self) -> bool:
        return self._ready


###########################################################################
# ─── STT WEBSOCKET CLIENTS  (was: stt_clients.py)
###########################################################################

"""
Streaming STT clients.

- Deepgram Flux — Deepgram SDK, v2/listen, model-integrated end-of-turn
- Deepgram Nova — Raw WebSocket, v1/listen, endpointing-based
"""

import asyncio
import json
import logging
from typing import Callable, Awaitable, Optional

import websockets
from websockets.exceptions import ConnectionClosed

logger = logging.getLogger(__name__)

_DG_V1_WS_URL = "wss://api.deepgram.com/v1/listen"
_KEEPALIVE_INTERVAL = 8


def _is_flux_model(model: str) -> bool:
    return model.startswith("flux")


# ═══════════════════════════════════════════════════════════════════════════
# Flux via Deepgram SDK (v2 API) — connection-managed + full param control
# ═══════════════════════════════════════════════════════════════════════════


async def _stream_flux_sdk(
    audio_queue: asyncio.Queue,
    transcript_callback: Callable,
    api_key: str,
    sample_rate: int = 16000,
    keywords: Optional[list] = None,
    start_of_turn_callback: Optional[Callable] = None,
    end_of_turn_callback: Optional[Callable] = None,
    eager_eot_callback: Optional[Callable] = None,
    turn_resumed_callback: Optional[Callable] = None,
    eot_threshold: float = 0.65,
    eager_eot_threshold: Optional[float] = 0.35,
    eot_timeout_ms: int = 1500,
) -> None:
    """Stream audio to Deepgram Flux using the official SDK.

    SDK handles connection lifecycle (keepalive, SSL, reconnection).
    Flux-specific params passed as kwargs → SDK maps to URL query params.
    """
    from deepgram import AsyncDeepgramClient
    from deepgram.core.events import EventType

    client = AsyncDeepgramClient(api_key=api_key)

    # Build SDK connection kwargs — all become URL query params
    connect_kwargs = {
        "model": "flux-general-en",
        "encoding": "linear16",
        "sample_rate": str(sample_rate),
        "eot_threshold": str(eot_threshold),
        "eot_timeout_ms": str(eot_timeout_ms),
    }
    if eager_eot_threshold is not None:
        connect_kwargs["eager_eot_threshold"] = str(eager_eot_threshold)
    if keywords:
        connect_kwargs["keyterm"] = keywords

    logger.info(
        "Flux SDK: connecting | eot=%.2f eager=%s timeout=%dms | %d keyterm(s)",
        eot_threshold,
        f"{eager_eot_threshold:.2f}" if eager_eot_threshold else "off",
        eot_timeout_ms,
        len(keywords) if keywords else 0,
    )

    async with client.listen.v2.connect(**connect_kwargs) as connection:
        _done = asyncio.Event()

        async def on_message(message):
            msg_type = getattr(message, "type", "")

            if msg_type == "Connected":
                logger.info("Flux SDK: Connected")
                return

            if msg_type == "TurnInfo":
                event = getattr(message, "event", "")
                transcript = (getattr(message, "transcript", "") or "").strip()
                turn_index = getattr(message, "turn_index", 0)
                eot_confidence = getattr(message, "end_of_turn_confidence", 0.0)

                if event == "StartOfTurn":
                    logger.info("Flux SDK: StartOfTurn | turn=%d", turn_index)
                    if start_of_turn_callback:
                        try:
                            await start_of_turn_callback()
                        except Exception as e:
                            logger.error("start_of_turn_callback: %s", e)

                elif event == "Update":
                    if transcript:
                        await transcript_callback(transcript, False, None)

                elif event == "EagerEndOfTurn":
                    if transcript:
                        logger.info(
                            "Flux SDK: EagerEOT conf=%.2f text=%r",
                            eot_confidence,
                            transcript[:60],
                        )
                        # Send as interim (not final) — EndOfTurn will confirm
                        await transcript_callback(transcript, False, None)
                        # Fire speculative callback for pre-computation
                        if eager_eot_callback:
                            try:
                                await eager_eot_callback(transcript, eot_confidence)
                            except Exception as e:
                                logger.error("eager_eot_callback: %s", e)

                elif event == "TurnResumed":
                    logger.info("Flux SDK: TurnResumed | turn=%d", turn_index)
                    if transcript:
                        await transcript_callback(transcript, False, None)
                    # Cancel any speculative processing
                    if turn_resumed_callback:
                        try:
                            await turn_resumed_callback()
                        except Exception as e:
                            logger.error("turn_resumed_callback: %s", e)

                elif event == "EndOfTurn":
                    logger.info(
                        "Flux SDK: EndOfTurn conf=%.2f text=%r",
                        eot_confidence,
                        transcript[:60],
                    )
                    if transcript:
                        await transcript_callback(transcript, True, None)
                    if end_of_turn_callback:
                        try:
                            await end_of_turn_callback(eot_confidence)
                        except Exception as e:
                            logger.error("end_of_turn_callback: %s", e)
                return

            # Fallback for unexpected message formats
            if hasattr(message, "transcript") and message.transcript:
                t = message.transcript.strip()
                if t:
                    is_final = getattr(message, "is_final", False) or getattr(
                        message, "speech_final", False
                    )
                    await transcript_callback(t, is_final, None)

        def on_close(_):
            logger.info("Flux SDK: closed")
            _done.set()

        def on_error(error):
            logger.error("Flux SDK: error: %s", error)

        connection.on(EventType.OPEN, lambda _: logger.info("Flux SDK: opened"))
        connection.on(EventType.MESSAGE, on_message)
        connection.on(EventType.CLOSE, on_close)
        connection.on(EventType.ERROR, on_error)

        listen_task = asyncio.create_task(connection.start_listening())

        # Feed audio from queue
        try:
            while not _done.is_set():
                try:
                    chunk = await asyncio.wait_for(audio_queue.get(), timeout=1.0)
                except asyncio.TimeoutError:
                    continue
                if chunk is None:
                    break
                try:
                    await connection._send(chunk)
                except Exception as e:
                    logger.warning("Flux SDK: send error: %s", e)
                    break
        except asyncio.CancelledError:
            pass
        except Exception as e:
            logger.error("Flux SDK: feed error: %s", e)

        try:
            listen_task.cancel()
            await asyncio.sleep(0.1)
        except Exception:
            pass

    logger.info("Flux SDK: session ended")


# ═══════════════════════════════════════════════════════════════════════════
# Nova via raw WebSocket (v1 API)
# ═══════════════════════════════════════════════════════════════════════════


async def _stream_nova_ws(
    audio_queue: asyncio.Queue,
    transcript_callback: Callable,
    api_key: str,
    model: str = "nova-3",
    language: str = "en",
    endpointing: int = 400,
    sample_rate: int = 16000,
    speech_started_callback: Optional[Callable] = None,
    keywords: Optional[list] = None,
    enable_sentiment: bool = True,
) -> None:
    """Stream audio to Deepgram Nova via raw WebSocket (v1 API)."""
    url = (
        f"{_DG_V1_WS_URL}"
        f"?model={model}&encoding=linear16&sample_rate={sample_rate}"
        f"&channels=1&interim_results=true&smart_format=true"
        f"&punctuate=true&filler_words=false"
        f"&endpointing={endpointing}&vad_events=true"
        f"&utterance_end_ms=2000&language={language}"
    )
    if enable_sentiment:
        url += "&sentiment=true"
    if keywords:
        kw_param = "keyterm" if model.startswith("nova-3") else "keywords"
        url += "".join(f"&{kw_param}={kw}" for kw in keywords)
    headers = {"Authorization": f"Token {api_key}"}

    for attempt in range(3):
        try:
            async with websockets.connect(url, additional_headers=headers) as dg_ws:
                logger.info(
                    "Nova STT connected | model=%s | endpointing=%dms",
                    model,
                    endpointing,
                )
                close_event = asyncio.Event()

                async def send_audio():
                    try:
                        while True:
                            chunk = await audio_queue.get()
                            if chunk is None:
                                try:
                                    await dg_ws.send(
                                        json.dumps({"type": "CloseStream"})
                                    )
                                except ConnectionClosed:
                                    pass
                                close_event.set()
                                break
                            try:
                                await dg_ws.send(chunk)
                            except ConnectionClosed:
                                break
                    except asyncio.CancelledError:
                        pass

                async def keepalive():
                    try:
                        while True:
                            await asyncio.sleep(_KEEPALIVE_INTERVAL)
                            await dg_ws.send(json.dumps({"type": "KeepAlive"}))
                    except (ConnectionClosed, asyncio.CancelledError):
                        pass

                async def recv():
                    try:
                        while True:
                            try:
                                raw = await asyncio.wait_for(dg_ws.recv(), timeout=30)
                            except asyncio.TimeoutError:
                                await dg_ws.close()
                                break
                            data = json.loads(raw)
                            mt = data.get("type")
                            if mt == "Results":
                                alts = data.get("channel", {}).get("alternatives", [])
                                if not alts:
                                    continue
                                text = alts[0].get("transcript", "").strip()
                                is_final = data.get("is_final", False) or data.get(
                                    "speech_final", False
                                )
                                sentiment = (
                                    alts[0].get("sentiment", None)
                                    if enable_sentiment
                                    else None
                                )
                                sentiment_score = (
                                    alts[0].get("sentiment_score", None)
                                    if enable_sentiment
                                    else None
                                )
                                if text:
                                    await transcript_callback(
                                        text, is_final, sentiment, sentiment_score
                                    )
                                if close_event.is_set() and is_final:
                                    await dg_ws.close()
                                    return
                            elif mt == "SpeechStarted" and speech_started_callback:
                                try:
                                    await speech_started_callback()
                                except Exception:
                                    pass
                            elif mt == "UtteranceEnd" and close_event.is_set():
                                await dg_ws.close()
                                return
                    except ConnectionClosed:
                        pass
                    except Exception as e:
                        logger.error("Nova recv error: %s", e)

                ka = asyncio.create_task(keepalive())
                try:
                    await asyncio.gather(send_audio(), recv())
                finally:
                    ka.cancel()
            return
        except (ConnectionClosed, OSError) as e:
            if attempt < 2:
                logger.warning("Nova disconnected (attempt %d/3): %s", attempt + 1, e)
                await asyncio.sleep(0.5 * (attempt + 1))
        except Exception as e:
            logger.error("Nova error: %s", e)
            raise


# ═══════════════════════════════════════════════════════════════════════════
# Dispatcher
# ═══════════════════════════════════════════════════════════════════════════


async def stream_deepgram(
    audio_queue: asyncio.Queue,
    transcript_callback: Callable[[str, bool], Awaitable[None]],
    api_key: str,
    model: str = "nova-3",
    language: str = "en",
    endpointing: int = 400,
    sample_rate: int = 16000,
    speech_started_callback: Optional[Callable[[], Awaitable[None]]] = None,
    keywords: Optional[list] = None,
    enable_sentiment: bool = True,
    detect_language: bool = False,
    language_callback: Optional[Callable[[str], Awaitable[None]]] = None,
    start_of_turn_callback: Optional[Callable[[], Awaitable[None]]] = None,
    end_of_turn_callback: Optional[Callable[[float], Awaitable[None]]] = None,
    # Flux-specific params (ignored for Nova)
    eager_eot_callback: Optional[Callable] = None,
    turn_resumed_callback: Optional[Callable] = None,
    eot_threshold: float = 0.65,
    eager_eot_threshold: Optional[float] = 0.35,
    eot_timeout_ms: int = 1500,
) -> None:
    """Route to Flux SDK or Nova raw WebSocket based on model."""
    if _is_flux_model(model):
        logger.info("Routing to Flux SDK (v2)")
        await _stream_flux_sdk(
            audio_queue=audio_queue,
            transcript_callback=transcript_callback,
            api_key=api_key,
            sample_rate=sample_rate,
            keywords=keywords,
            start_of_turn_callback=start_of_turn_callback,
            end_of_turn_callback=end_of_turn_callback,
            eager_eot_callback=eager_eot_callback,
            turn_resumed_callback=turn_resumed_callback,
            eot_threshold=eot_threshold,
            eager_eot_threshold=eager_eot_threshold,
            eot_timeout_ms=eot_timeout_ms,
        )
    else:
        logger.info("Routing to Nova WebSocket (v1)")
        await _stream_nova_ws(
            audio_queue=audio_queue,
            transcript_callback=transcript_callback,
            api_key=api_key,
            model=model,
            language=language,
            endpointing=endpointing,
            sample_rate=sample_rate,
            speech_started_callback=speech_started_callback,
            keywords=keywords,
            enable_sentiment=enable_sentiment,
        )


###########################################################################
# ─── FLUX SESSION MANAGER  (was: flux_session_manager.py)
###########################################################################

"""
flux_session_manager.py — Per-speaker Flux STT session management

Manages N parallel Deepgram Flux connections, one per participant in a
multi-party meeting. Each participant gets their own dedicated Flux session
for accurate per-speaker turn detection and transcription.

Architecture:
    Recall.ai audio_separate_raw events (tagged with participant_id)
        ↓
    FluxSessionManager.route_audio(participant_id, participant_name, pcm)
        ↓
    Per-speaker FluxSession (lazy-created)
        ↓
    stream_deepgram() with flux-general-en model
        ↓
    transcripts routed back via on_final/on_interim callbacks
        (with speaker attribution)

Lifecycle:
    - Session created lazily on first audio chunk for a participant
    - Session closed when participant leaves meeting
    - All sessions closed on manager shutdown
    - If a session dies mid-meeting, it auto-recreates on next audio chunk

Standup mode note: This manager is ONLY used in client mode. Standup mode
keeps its existing single-Flux connection (self._stt_task in BotSession).
"""

import asyncio
import time
from typing import Awaitable, Callable, Optional


# Flux expects 80ms chunks at 16kHz mono linear16 = 2560 bytes
# (16000 samples/sec * 0.080 sec * 2 bytes/sample)
FLUX_CHUNK_SIZE = 2560
FLUX_SAMPLE_RATE = 16000

# Flux STT parameters (tuned for client meetings)
# Higher eot_threshold = wait longer for confident turn end
# Lower eot_timeout_ms = force turn end sooner on ambiguous silence
FLUX_EOT_THRESHOLD = 0.75  # 0-1; higher = more confident EOT required
FLUX_EAGER_EOT_THRESHOLD = 0.35  # 0-1; when to emit EagerEndOfTurn
FLUX_EOT_TIMEOUT_MS = 1500  # force EOT after this much silence


class FluxSession:
    """One Flux connection for one participant."""

    def __init__(self, participant_id: str, participant_name: str):
        self.participant_id = participant_id
        self.participant_name = participant_name
        self.audio_queue: asyncio.Queue = asyncio.Queue()
        self.audio_buffer: bytes = b""
        self.flux_task: Optional[asyncio.Task] = None
        self.last_interim: str = ""
        self.created_at: float = time.time()
        self.is_alive: bool = True
        # Per-session error tracking
        self.consecutive_errors: int = 0

    def __repr__(self):
        age = time.time() - self.created_at
        return (
            f"<FluxSession {self.participant_name} "
            f"(id={self.participant_id[:8]}, age={age:.0f}s, "
            f"alive={self.is_alive})>"
        )


class FluxSessionManager:
    """Manages N Flux sessions, one per participant.

    Usage (in BotSession, client mode only):

        # Stage R: api_key now comes from key_rotator.key_for_session(),
        # bound to this session for its entire lifetime.
        from key_rotator import key_for_session
        self._flux_manager = FluxSessionManager(
            api_key=key_for_session("DEEPGRAM", session_id),
            on_final=self._on_flux_final_client,
            on_interim=self._on_flux_interim_client,
        )

        # On audio_separate_raw.data event:
        await self._flux_manager.route_audio(
            participant_id, participant_name, pcm_bytes
        )

        # On participant_events.leave event:
        await self._flux_manager.close_session(participant_id)

        # On session end:
        await self._flux_manager.close_all()
    """

    def __init__(
        self,
        api_key: str,
        on_final: Callable[[str, str, Optional[dict]], Awaitable[None]],
        on_interim: Callable[[str, str, Optional[dict]], Awaitable[None]],
        keyterms: Optional[list] = None,
        tag: str = "",
    ):
        """
        Args:
            api_key: Deepgram API key
            on_final: async callback (speaker_name, text) called on final transcript
            on_interim: async callback (speaker_name, text) called on interim transcript
            keyterms: optional list of keyterms for domain vocab boost
            tag: log prefix for this manager's session (e.g., "[S:abc123]")
        """
        self._api_key = api_key
        self._on_final = on_final
        self._on_interim = on_interim
        self._keyterms = keyterms or []
        self._tag = tag
        self._sessions: dict[str, FluxSession] = {}
        self._closing: bool = False
        # Lock to serialize session creation (prevents race on first audio)
        self._create_lock = asyncio.Lock()

    # ── Public API ──────────────────────────────────────────────────────

    async def route_audio(
        self,
        participant_id: str,
        participant_name: str,
        pcm_bytes: bytes,
    ) -> None:
        """Route audio to the correct per-speaker Flux session.

        Lazy-creates a session if this is the first audio for this participant.
        Silently drops audio if manager is closing.
        """
        if self._closing or not pcm_bytes:
            return

        # Lazy-create session if needed
        session = self._sessions.get(participant_id)
        if session is None or not session.is_alive:
            session = await self._get_or_create_session(
                participant_id, participant_name
            )
            if session is None:
                return  # creation failed

        # Re-chunk audio to Flux's expected 80ms boundary
        session.audio_buffer += pcm_bytes
        while len(session.audio_buffer) >= FLUX_CHUNK_SIZE:
            chunk = session.audio_buffer[:FLUX_CHUNK_SIZE]
            session.audio_buffer = session.audio_buffer[FLUX_CHUNK_SIZE:]
            try:
                await session.audio_queue.put(chunk)
            except Exception as e:
                print(
                    f"[FluxManager] {self._tag} ⚠️  Queue put failed for "
                    f"{session.participant_name}: {e}"
                )
                session.is_alive = False
                break

    async def close_session(self, participant_id: str) -> None:
        """Close a single participant's Flux session (e.g., they left meeting)."""
        session = self._sessions.pop(participant_id, None)
        if session is None:
            return
        await self._close_session_internal(session)
        print(
            f"[FluxManager] {self._tag} 🔌 Closed session for "
            f"{session.participant_name}"
        )

    async def close_all(self) -> None:
        """Close all active Flux sessions. Call on bot leave / session end."""
        self._closing = True
        if not self._sessions:
            return

        sessions = list(self._sessions.values())
        self._sessions.clear()
        print(f"[FluxManager] {self._tag} 🔌 Closing {len(sessions)} session(s)")

        # Close all in parallel
        await asyncio.gather(
            *(self._close_session_internal(s) for s in sessions),
            return_exceptions=True,
        )

    def get_active_speakers(self) -> list[str]:
        """Return names of participants with active Flux sessions."""
        return [s.participant_name for s in self._sessions.values() if s.is_alive]

    def session_count(self) -> int:
        """Total active sessions (diagnostic)."""
        return sum(1 for s in self._sessions.values() if s.is_alive)

    # ── Internal ────────────────────────────────────────────────────────

    async def _get_or_create_session(
        self,
        participant_id: str,
        participant_name: str,
    ) -> Optional[FluxSession]:
        """Lazy-create or revive a session. Returns None on failure."""
        async with self._create_lock:
            # Re-check after acquiring lock (another coroutine may have created it)
            existing = self._sessions.get(participant_id)
            if existing and existing.is_alive:
                return existing

            # Create new session
            session = FluxSession(participant_id, participant_name)
            self._sessions[participant_id] = session

            # Start Flux task for this session
            session.flux_task = asyncio.create_task(self._run_flux_session(session))

            print(
                f"[FluxManager] {self._tag} 🆕 Created Flux session for "
                f"{participant_name} (id={participant_id[:8]})"
            )
            return session

    async def _run_flux_session(self, session: FluxSession) -> None:
        """Run stream_deepgram for one participant. Auto-restarts on error.

        Each session has its own audio queue, its own Flux WebSocket connection,
        and its own transcript callbacks tagged with the participant's name.
        """
        # Import here to avoid circular import at module load

        speaker = session.participant_name

        async def _on_transcript(
            text: str, is_final: bool, sentiment=None, sentiment_score=None
        ):
            """Called by stream_deepgram on every transcript (final + interim)."""
            text = (text or "").strip()
            if not text:
                return

            try:
                if is_final:
                    session.last_interim = ""  # clear interim after final
                    await self._on_final(speaker, text, sentiment, sentiment_score)
                else:
                    session.last_interim = text
                    await self._on_interim(speaker, text, sentiment, sentiment_score)
            except Exception as e:
                print(f"[FluxManager] {self._tag} ⚠️  Callback error for {speaker}: {e}")

        # Run Flux with auto-restart on error (up to 3 consecutive failures)
        while session.is_alive and not self._closing:
            try:
                await stream_deepgram(
                    audio_queue=session.audio_queue,
                    transcript_callback=_on_transcript,
                    api_key=self._api_key,
                    model="nova-3",
                    sample_rate=FLUX_SAMPLE_RATE,
                    keywords=self._keyterms if self._keyterms else None,
                    enable_sentiment=True,
                )
                # If stream_deepgram returns normally, the session is done
                print(
                    f"[FluxManager] {self._tag} 🏁 Flux session ended "
                    f"cleanly for {speaker}"
                )
                break

            except asyncio.CancelledError:
                # Cancellation during cleanup — don't restart
                break

            except Exception as e:
                session.consecutive_errors += 1
                print(
                    f"[FluxManager] {self._tag} ⚠️  Flux error for {speaker} "
                    f"(attempt {session.consecutive_errors}/3): {e}"
                )

                if session.consecutive_errors >= 3:
                    print(
                        f"[FluxManager] {self._tag} ❌ Giving up on "
                        f"{speaker} after 3 consecutive errors"
                    )
                    session.is_alive = False
                    break

                # Back off briefly before retrying
                await asyncio.sleep(1.0 * session.consecutive_errors)

        session.is_alive = False

    async def _close_session_internal(self, session: FluxSession) -> None:
        """Cleanly close one session: signal queue end + cancel task."""
        session.is_alive = False

        # Signal stream_deepgram to close by putting None on queue
        try:
            await asyncio.wait_for(
                session.audio_queue.put(None),
                timeout=1.0,
            )
        except (asyncio.TimeoutError, Exception):
            pass

        # Cancel the task if still running
        if session.flux_task and not session.flux_task.done():
            session.flux_task.cancel()
            try:
                await asyncio.wait_for(session.flux_task, timeout=2.0)
            except (asyncio.TimeoutError, asyncio.CancelledError, Exception):
                pass
